# Generated by Django 5.2.17 on 2026-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_duration_minutes_task_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startd_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
