# Generated by Django 5.2.17 on 2026-08-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_tasknotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskNotes',
            new_name='TaskNote',
        ),
    ]
